# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Deploy
    displayName: 部署到服务器
    jobs:
      - deployment: VMDeploy
        displayName: 部署到Uni服务器
        environment:
          name: uni-tencent
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 1
                  displayName: 切换到目标仓库分支
                - bash: |-
                    docker compose -f docker-compose.yml up --build -d
                  env:
                    DeployPort: 9090
                  displayName: 运行 docker compose 命令

